spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.64.140
    username: admin
    password: admin
  zipkin:
    sender:
      type: rabbit
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2